### ISSUE TITLE
Post pagination

### ISSUE THREAD

**Issue by ckunte** [dz/chisel#5]
Hi David: Is there a way to add post pagination (with next, previous) links to individual posts? Would be grateful for advice and suggestions for a tool as nimble as Chisel. Thanks in advance.

**Comment by ckunte** [comment]
Hat tip to __Ankur Tyagi__ (many thanks @7h3rAm) for the template and forked code, from which, I was able to figure out how to make inter-post navigation work, and hence closing this issue, since the following now enables it.

1. Update `chisel.py` to include the following in the `detail_pages` generator (notably `entries=f` within `.render()`. (This enables access to all posts for count and slice / index operations to enable navigation.)

		@step
		def detail_pages(f, e):
		    for file in f:
		        write_file(file['url'], \
		            e.get_template('detail.html').render(entry=file, entries=f))	

2. Update `detail.html` to `set curr` and `set total`, and the entire loop and index code, followed by html mark-up to call next and previous posts. I prefer post navigation below my content:

		{% extends "base.html" %}
		{%- block post %}
		  {% set curr = entry.title %}
		  {% set total = entries | count %}

		  {{ entry.pretty_date }}

		  {{ entry.title }}

		  {{ entry.content }}

		  {# Inter-post navigation begins here #}

		    {%for entry in entries%}
		      {%if entry.title == curr%}
		        {%if loop.index0 > 0%}
		          {%set next = entries[loop.index0-1].url%}
		          {%set nexttitle = entries[loop.index0-1].title%}
		        {%else%}
		          {%set next = None%}
		          {%set nexttitle = None%}
		        {%endif%}
		        {%if loop.index0+1 < total%}
		          {%set prev = entries[loop.index0+1].url%}
		          {%set prevtitle = entries[loop.index0+1].title%}
		        {%else%}
		          {%set prev = None%}
		          {%set prevtitle = None%}
		        {%endif%}
		        <div class=nav>
		          <table>
		          {%if prev and next%}
		            <tr>
		              <td class="lt"><a title="{{prevtitle}}" href="/log/{{ prev }}">&larr; Previous</a></td>
		              <td><a class="navleft" href="/log/archive">Archive</a></td>
		              <td class="rt"><a title="{{nexttitle}}" href="/log/{{ next }}">Next &rarr;</a></td>
		            </tr>
		          {%elif not next%}
		          <tr>
		            <td class="lt"><a title="{{prevtitle}}" href="/log/{{ prev }}">&larr; Previous</a></td>
		            <td><a class="navleft" href="/log/archive">Archive</a></td>
		            <td style="width:50%; text-align:right;">&nbsp;</td>
		          </tr>
		          {%elif not prev%}
		            <tr>
		              <td class="lt">&nbsp;</td>
		              <td><a class="navleft" href="/log/archive">Archive</a></td>
		              <td class="rt"><a title="{{nexttitle}}" href="/log/{{ next }}">Next &rarr;</a></td>
		            </tr>
		          {%endif%}
		          </table>
		        </div>
		      {%endif%}
		    {%endfor%}
		  {# Inter-post navigation ends here #}    
		  {%- endblock %} {# end post #}

**Comment by 7h3rAm** [comment]
@ckunte Thanks to you as my fork is based on yours and glad my mods helped solve this issue.
